# Generated by Django 4.2.7 on 2025-06-02 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalyreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='logbatch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='anomalyreport',
            name='logs_anomal_detecte_0c19df_idx',
        ),
        migrations.RemoveIndex(
            model_name='anomalyreport',
            name='logs_anomal_anomaly_89bf0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='logentry',
            name='logs_logent_source_d42def_idx',
        ),
        migrations.RenameField(
            model_name='logbatch',
            old_name='processed_entries',
            new_name='processed_logs',
        ),
        migrations.RenameField(
            model_name='logbatch',
            old_name='total_entries',
            new_name='total_logs',
        ),
        migrations.RemoveField(
            model_name='anomalyreport',
            name='anomaly_type',
        ),
        migrations.RemoveField(
            model_name='anomalyreport',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='anomalyreport',
            name='detected_at',
        ),
        migrations.RemoveField(
            model_name='anomalyreport',
            name='detection_method',
        ),
        migrations.RemoveField(
            model_name='anomalyreport',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='anomalyreport',
            name='model_version',
        ),
        migrations.RemoveField(
            model_name='anomalyreport',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='anomalyreport',
            name='suggested_action',
        ),
        migrations.RemoveField(
            model_name='logbatch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='logbatch',
            name='log_entries',
        ),
        migrations.RemoveField(
            model_name='logbatch',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='parsed_data',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='raw_log',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='request_method',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='anomalyreport',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalyreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalyreport',
            name='title',
            field=models.CharField(default='Anomaly Detection Alert', max_length=200),
        ),
        migrations.AddField(
            model_name='logbatch',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logbatch',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='log_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logentry',
            name='anomaly_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anomalyreport',
            name='confidence_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='anomalyreport',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='anomalyreport',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_reports', to='logs.logentry'),
        ),
        migrations.AlterField(
            model_name='anomalyreport',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='anomalyreport',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='logbatch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logbatch',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='anomalyreport',
            index=models.Index(fields=['severity'], name='logs_anomal_severit_b7759f_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['anomaly_score'], name='logs_logent_anomaly_593f2f_idx'),
        ),
    ]
